### ISSUE TITLE
Github Action for the NextJS Build

### ISSUE THREAD

**Issue by mgan59** [gitbabel/starter-nextjs-tailwindcss#13]
## Context

We enabled the Dependabot github action which is now running daily security audits.  We need to setup a build check to ensure and automate that security patches don't break our build(s).

## Actions

Setup a new github action to run our `npm run build` command on a pull-request

__Sample Code for Action...__

```yaml
name: RUN NEXTJS BUILD

# Reference
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-nodejs-with-github-actions
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:

    name: NEXTJS BUILD
    # This job runs on Linux
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Install Node
        # Setups the npm installer to know which private registry to pull from
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@gitbabel'
      - name: NPM INSTALL
        run: npm install
      - name: Run Build
        run: npm run build
```

> Verify above code works and make adjustments
